//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesApp.CreateRecipeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ingredient", Namespace="http://schemas.datacontract.org/2004/07/WSDL_Services")]
    [System.SerializableAttribute()]
    public partial class Ingredient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recipe", Namespace="http://schemas.datacontract.org/2004/07/WSDL_Services")]
    [System.SerializableAttribute()]
    public partial class Recipe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RecipesApp.CreateRecipeService.Ingredient[] IngredientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RecipesApp.CreateRecipeService.Ingredient[] Ingredients {
            get {
                return this.IngredientsField;
            }
            set {
                if ((object.ReferenceEquals(this.IngredientsField, value) != true)) {
                    this.IngredientsField = value;
                    this.RaisePropertyChanged("Ingredients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreateRecipeService.ICreateRecipeService")]
    public interface ICreateRecipeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateRecipeService/SearchIngredients", ReplyAction="http://tempuri.org/ICreateRecipeService/SearchIngredientsResponse")]
        RecipesApp.CreateRecipeService.Ingredient[] SearchIngredients(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateRecipeService/SearchIngredients", ReplyAction="http://tempuri.org/ICreateRecipeService/SearchIngredientsResponse")]
        System.Threading.Tasks.Task<RecipesApp.CreateRecipeService.Ingredient[]> SearchIngredientsAsync(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateRecipeService/AddToRecipe", ReplyAction="http://tempuri.org/ICreateRecipeService/AddToRecipeResponse")]
        void AddToRecipe(string fileName, int ingredientId, string recipeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateRecipeService/AddToRecipe", ReplyAction="http://tempuri.org/ICreateRecipeService/AddToRecipeResponse")]
        System.Threading.Tasks.Task AddToRecipeAsync(string fileName, int ingredientId, string recipeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateRecipeService/GetCreatedRecipes", ReplyAction="http://tempuri.org/ICreateRecipeService/GetCreatedRecipesResponse")]
        RecipesApp.CreateRecipeService.Recipe[] GetCreatedRecipes(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateRecipeService/GetCreatedRecipes", ReplyAction="http://tempuri.org/ICreateRecipeService/GetCreatedRecipesResponse")]
        System.Threading.Tasks.Task<RecipesApp.CreateRecipeService.Recipe[]> GetCreatedRecipesAsync(string fileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreateRecipeServiceChannel : RecipesApp.CreateRecipeService.ICreateRecipeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateRecipeServiceClient : System.ServiceModel.ClientBase<RecipesApp.CreateRecipeService.ICreateRecipeService>, RecipesApp.CreateRecipeService.ICreateRecipeService {
        
        public CreateRecipeServiceClient() {
        }
        
        public CreateRecipeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreateRecipeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateRecipeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateRecipeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RecipesApp.CreateRecipeService.Ingredient[] SearchIngredients(string query) {
            return base.Channel.SearchIngredients(query);
        }
        
        public System.Threading.Tasks.Task<RecipesApp.CreateRecipeService.Ingredient[]> SearchIngredientsAsync(string query) {
            return base.Channel.SearchIngredientsAsync(query);
        }
        
        public void AddToRecipe(string fileName, int ingredientId, string recipeName) {
            base.Channel.AddToRecipe(fileName, ingredientId, recipeName);
        }
        
        public System.Threading.Tasks.Task AddToRecipeAsync(string fileName, int ingredientId, string recipeName) {
            return base.Channel.AddToRecipeAsync(fileName, ingredientId, recipeName);
        }
        
        public RecipesApp.CreateRecipeService.Recipe[] GetCreatedRecipes(string fileName) {
            return base.Channel.GetCreatedRecipes(fileName);
        }
        
        public System.Threading.Tasks.Task<RecipesApp.CreateRecipeService.Recipe[]> GetCreatedRecipesAsync(string fileName) {
            return base.Channel.GetCreatedRecipesAsync(fileName);
        }
    }
}
