//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesApp.RecipeSearchWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RecipeSearchWeb.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Search", ReplyAction="http://tempuri.org/IService1/SearchResponse")]
        string Search(string query, string cuisine, string diet, string intolerances, int offset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Search", ReplyAction="http://tempuri.org/IService1/SearchResponse")]
        System.Threading.Tasks.Task<string> SearchAsync(string query, string cuisine, string diet, string intolerances, int offset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchFullRecipe", ReplyAction="http://tempuri.org/IService1/SearchFullRecipeResponse")]
        string SearchFullRecipe(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchFullRecipe", ReplyAction="http://tempuri.org/IService1/SearchFullRecipeResponse")]
        System.Threading.Tasks.Task<string> SearchFullRecipeAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : RecipesApp.RecipeSearchWeb.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<RecipesApp.RecipeSearchWeb.IService1>, RecipesApp.RecipeSearchWeb.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Search(string query, string cuisine, string diet, string intolerances, int offset) {
            return base.Channel.Search(query, cuisine, diet, intolerances, offset);
        }
        
        public System.Threading.Tasks.Task<string> SearchAsync(string query, string cuisine, string diet, string intolerances, int offset) {
            return base.Channel.SearchAsync(query, cuisine, diet, intolerances, offset);
        }
        
        public string SearchFullRecipe(int id) {
            return base.Channel.SearchFullRecipe(id);
        }
        
        public System.Threading.Tasks.Task<string> SearchFullRecipeAsync(int id) {
            return base.Channel.SearchFullRecipeAsync(id);
        }
    }
}
