//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesApp.SaveAndLoadRecipeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipeInfo", Namespace="http://schemas.datacontract.org/2004/07/WSDL_Services")]
    [System.SerializableAttribute()]
    public partial class RecipeInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceUrl {
            get {
                return this.SourceUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceUrlField, value) != true)) {
                    this.SourceUrlField = value;
                    this.RaisePropertyChanged("SourceUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SaveAndLoadRecipeService.ISaveAndLoadRecipeService")]
    public interface ISaveAndLoadRecipeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaveAndLoadRecipeService/SaveRecipesToXml", ReplyAction="http://tempuri.org/ISaveAndLoadRecipeService/SaveRecipesToXmlResponse")]
        void SaveRecipesToXml(int recipeId, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaveAndLoadRecipeService/SaveRecipesToXml", ReplyAction="http://tempuri.org/ISaveAndLoadRecipeService/SaveRecipesToXmlResponse")]
        System.Threading.Tasks.Task SaveRecipesToXmlAsync(int recipeId, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaveAndLoadRecipeService/ReadRecipesFromXml", ReplyAction="http://tempuri.org/ISaveAndLoadRecipeService/ReadRecipesFromXmlResponse")]
        RecipesApp.SaveAndLoadRecipeService.RecipeInfo[] ReadRecipesFromXml(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaveAndLoadRecipeService/ReadRecipesFromXml", ReplyAction="http://tempuri.org/ISaveAndLoadRecipeService/ReadRecipesFromXmlResponse")]
        System.Threading.Tasks.Task<RecipesApp.SaveAndLoadRecipeService.RecipeInfo[]> ReadRecipesFromXmlAsync(string fileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISaveAndLoadRecipeServiceChannel : RecipesApp.SaveAndLoadRecipeService.ISaveAndLoadRecipeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveAndLoadRecipeServiceClient : System.ServiceModel.ClientBase<RecipesApp.SaveAndLoadRecipeService.ISaveAndLoadRecipeService>, RecipesApp.SaveAndLoadRecipeService.ISaveAndLoadRecipeService {
        
        public SaveAndLoadRecipeServiceClient() {
        }
        
        public SaveAndLoadRecipeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SaveAndLoadRecipeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaveAndLoadRecipeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaveAndLoadRecipeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SaveRecipesToXml(int recipeId, string fileName) {
            base.Channel.SaveRecipesToXml(recipeId, fileName);
        }
        
        public System.Threading.Tasks.Task SaveRecipesToXmlAsync(int recipeId, string fileName) {
            return base.Channel.SaveRecipesToXmlAsync(recipeId, fileName);
        }
        
        public RecipesApp.SaveAndLoadRecipeService.RecipeInfo[] ReadRecipesFromXml(string fileName) {
            return base.Channel.ReadRecipesFromXml(fileName);
        }
        
        public System.Threading.Tasks.Task<RecipesApp.SaveAndLoadRecipeService.RecipeInfo[]> ReadRecipesFromXmlAsync(string fileName) {
            return base.Channel.ReadRecipesFromXmlAsync(fileName);
        }
    }
}
